# $Id$
# Works with both GNU and BSD make 
#

PROGNAME=	cdpc

CC= gcc
SOURCES=	main.c cdp.c output_plain.c output_csv.c dlpi_getmac.c

CFLAGS+= -g -Wall
LDFLAGS+= -lpcap -lsocket -lnsl

all:
	${CC} ${CFLAGS} ${SOURCES} ${LDFLAGS} -o ${PROGNAME}

clean:
	rm -f *.o *~ ${PROGNAME} ${PROGNAME}.core core

